export const sections = [
  {
    key: 'menu',
    header: 'Изучить меню',
    subheader: 'Карточки блюд + AI-помощник',
    backgroundImage: '/finch-dish.jpg',
    buttonText: 'К меню',
    onClickRoute: '/menu',
  },
  {
    key: 'drinks',
    header: 'Изучить напитки',
    subheader: 'Карточки напитков + AI-помощник',
    backgroundImage: '/finch-drinks.jpg',
    buttonText: 'К напиткам',
    onClickRoute: '/drinks',
  },
  {
    key: 'service',
    header: 'Информация по сервису',
    subheader: 'Стандарты обслуживания и рекомендации',
    backgroundImage: '/finch-service.jpg',
    buttonText: 'Подробнее',
    onClickRoute: '/service',
  },
  {
    key: 'tests',
    header: 'Пройти тесты',
    subheader: 'Проверь знания, AI проверит ответы',
    backgroundImage: '/finch-tests.jpg',
    buttonText: 'Начать тест',
    onClickRoute: '/tests',
  },
  {
    key: 'ask',
    header: 'Общий вопрос',
    subheader: 'Задай любой вопрос о работе',
    backgroundImage: '/finch-ask.jpg',
    buttonText: 'Спросить',
    onClickRoute: '/ask',
  },
  {
    key: 'profile',
    header: 'Профиль',
    subheader: 'Карточка сотрудника и статистика',
    backgroundImage: '/finch-profile.jpg',
    buttonText: 'Открыть',
    onClickRoute: '/profile',
  },
]